#DEV environment

app:
  message: This is property file to the DEV${spring.application.name}

spring:
  datasource:
  driver-class-name: org.h2.Driver
url: jdbc:h2:mem;DB_CLOSE_DELAY=-1
username: sa
password: sa